### ISSUE TITLE
The changes in the payload are not getting reflect

### ISSUE THREAD

**Issue by aravindsridharamoorthy** [Rbillon59/wiremock-loadtest#6]
First of all thanks for sharing the knowledge.

In the kubernetes,yaml file in the location wiremock-loadtest\k8s, I removed ConfigMap in the end.

I wanted to pick the json content from wiremock-loadtest\mappings

Edited the static.json file's key values

"url": "/test"

"productName": "Dravid",

deleted all deployments and services and redeployed the changes using kubectl apply. 

However the path is working with /static only. Not sure where it being picked.

**Comment by Rbillon59** [comment]
Hello @aravindsridharamoorthy !

So I've to say thanks you for pointing this out. I learnt something today !

When you create a **configMap resource** inside the cluster, it is stored on the **master node in the etcd key value store**  
Then when the pod is scheduled, the configMap is stored in the local filesystem of the node and mounted in the pod following the yaml specs.

But your problem is not there. Since you deleted the configMap **before** deleting all the deployment and creating again "without" the configMap, the configMap were not deleted. And because you didn't remove the mount point on the pod specs, the configMap is already there.

Let me explain : 

From the beginning : After cloning from master :

```Shell
kubectl apply -R -f k8s/
```

![image](https://user-images.githubusercontent.com/17565349/151323772-2a5e01d5-d067-4dbb-ac7f-2da9e44df5a5.png)


![image](https://user-images.githubusercontent.com/17565349/151323894-786e6271-e3b2-4ab0-abf4-38be85dd64bf.png)


```Shell
curl localhost:35873/static
```
Response : From configmap !

```JSON
{
  "data": [
    {
      "type": "product",
      "id": "1",
      "attributes": {
        "productName": "Raspberry PI",
        "productDescription": "Best product ever",
        "price": 42,
        "stock": 500
      }
    }
  ]
}
```

Then deleting the `configmap` from `k8s/deployment.yaml`  : 

![image](https://user-images.githubusercontent.com/17565349/151324327-8c0964c1-cdf5-4b1a-a8ee-47fd671d956e.png)


Lets delete the resources : 

```Shell
kubectl delete -R -f k8s
```

![image](https://user-images.githubusercontent.com/17565349/151324605-48a3cef1-3316-4719-a6c5-226d7bb7b931.png)


Note the missing configmap deletion.

And if I apply again : 


```Shell
kubectl apply -R -f k8s/
```

```Shell
curl localhost:35873/static
```
Response : From again from configmap !

```JSON
{
  "data": [
    {
      "type": "product",
      "id": "1",
      "attributes": {
        "productName": "Raspberry PI",
        "productDescription": "Best product ever",
        "price": 42,
        "stock": 500
      }
    }
  ]
}
```

So. My bad I didn't document enough how to play with the mappings from files. In fact, the mappings are stored in configmap for simplicity because while it's stored on the master, it's available to each nodes and you don't have to deal with shared volumes inside your cluster.

There is different approach depending how you are managing your kubernetes cluster. But if it's for testing purpose and you have a limited amount of nodes inside your cluster, the simplest deal is still to play with `configMaps` or `hostPath` spec to `mount` the folder from the node to the pod.

For your use case, I would recommend to update the `configMap` by creating it from the mappings folder content with : 

```Shell
kubectl create configmap wiremock-mapping --from-file=mappings
```

This will take your payload from the  `mappings` folder. 

To update the mappings in the configMap from the mappings folder, run the following : 

```Shell
kubectl create configmap wiremock-mapping --from-file=mappings -o yaml --dry-run | kubectl replace -f -
# Restart the pods so they get the right version of the configMap
kubectl delete pods -l type=wiremock
```

**Comment by aravindsridharamoorthy** [comment]
Merci... the command worked for me.

I have 2 more questions

1. Can we add kubectl create configmap wiremock-mapping --from-file=mappings -o yaml --dry-run  as part of the kubernetes.yaml file
2. I am using minikube in docker desktop. When I try to hit localhost:8080/static or localhost:30308/static, I am getting "cant reach".


C:\Users\aravi\wiremock-loadtest\k8s>kubectl get all
NAME                            READY   STATUS    RESTARTS   AGE
pod/wiremock-545d8f85db-lkqk9   1/1     Running   0          78s

NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/kubernetes     ClusterIP      10.96.0.1      <none>        443/TCP          21h
service/wiremock-svc   LoadBalancer   10.99.148.60   <pending>     **8080:30308/TCP**   78s

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/wiremock   1/1     1            1           78s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/wiremock-545d8f85db   1         1         1       78s

NAME                                               REFERENCE             TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/hpa-wiremock   Deployment/wiremock   0%/30%    1         5         1          78s

I use "minikube service wiremock-svc --url" to generate url and port number. I can't provide this as an endpoint to upstream systems as this keeps changing everytime. Let me know what I should do for that?

Regards
Aravind

**Comment by Rbillon59** [comment]
Hi Aravind,

I'll keep this issue open since I definitely need to add some documentation about how to play with the configmaps as I told you in this issue.

1. Adding the command as part of the kubernetes.yaml, no, but documenting it properly in the README, yes !
2. You should be able to hit the mock from your `LoadBalancer` resource. To get it dynamically from scripts, you can run 

```Shell
kubectl get services -l wiremock --output jsonpath='{..ip}'
```

**Comment by aravindsridharamoorthy** [comment]
Hi Rbillion, Will this work in EKS? If we have 100s of mock response with big json file, won't this affect performance considering everything gets stored in configmap and used from there.

**Comment by aravindsridharamoorthy** [comment]
Considering that config Map file is limited to 1 MB

**Comment by Rbillon59** [comment]
For sure this will work in EKS.

For your 100s configuration files, configmap is not really a limitation but nonetheless not the best option.

On the performance view, configmap are stored as a file in the nodes and mounted to the pods behind the scenes so in any case, you'll use it in the same way.

The better option would be to use a distributed filesystem but not always easy to setup. 

It depends on the number of nodes you've. If you've few, hostPath would be enough. If not, distributed filesystem will be unavoidable I guess
